# syntax=docker/dockerfile:1.4
FROM node:18-alpine AS base

# Stage 1: tester
FROM base as tester

# Set the working directory
WORKDIR /app

RUN apk add --no-cache git

# Copy package.json and package-lock.json
COPY package.json ./

# Use a cache mount for npm
RUN --mount=type=cache,target=/opt/hostedtoolcache \
    npm set cache /opt/hostedtoolcache

# Cache node_modules to speed up builds
RUN --mount=type=cache,target=/app/node_modules \
    npm install --legacy-peer-deps

RUN npm run prisma-merge

RUN mkdir -p /app/public

COPY . .

# test the app
CMD ["npm", "test"]
