name: Build and Test- Main Branch

on:
  push:
    branches:
      - main

jobs:
  Coverage:
    runs-on: self-hosted
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2

  Update_permissions:
    runs-on: self-hosted
    needs: Coverage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: make env file
        run: echo "DATABASE_URL=mysql://node:nodenode@10.4.5.227:3306/dematicScrewfixTrenthamDashboard" > .env

      - name: Generate Prisma
        run: npm run prisma-merge

      - name: Update Permissions
        run: |
          npm run make-permissions

  Build_Image:
    runs-on: self-hosted
    needs: Coverage

    steps:
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: dematicscrewfixtrenthamdashboard
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t dematicscrewfixtrenthamdashboard:latest -f Dockerfile . --progress=plain --no-cache

      - name: Push Image
        run: |
          docker tag dematicscrewfixtrenthamdashboard:latest jwlyons/dematicscrewfixtrenthamdashboard:latest
          docker push jwlyons/dematicscrewfixtrenthamdashboard:latest
          docker tag dematicscrewfixtrenthamdashboard:latest jwlyons/dematicscrewfixtrenthamdashboard:${{ steps.metadata.outputs.version }}
          docker push jwlyons/dematicscrewfixtrenthamdashboard:${{ steps.metadata.outputs.version }}

      - name: Remove Docker Images
        run: |
          docker rmi dematicscrewfixtrenthamdashboard:latest
          docker rmi jwlyons/dematicscrewfixtrenthamdashboard:latest
          docker rmi jwlyons/dematicscrewfixtrenthamdashboard:${{ steps.metadata.outputs.version }}
