name: Test and Build Docker Image and Push to Docker Hub under testing tag
run-name: ${{ github.actor }} is  ${{ github.event_name }} on ${{ github.repository }}
on: 
  push:
    branches:
      - 'testing'
jobs:
  build:
    runs-on: self-hosted

    steps:
      - run: docker build -t dematicscrewfixtrenthamdashboard .
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          RUNNER_TOOL_CACHE: /toolcache

  publish-test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push to Docker Hub
        run: |
          docker tag dematicscrewfixtrenthamdashboard jwlyons/dematicscrewfixtrenthamdashboard:testing
          docker push jwlyons/dematicscrewfixtrenthamdashboard:testing

  update-container:
    runs-on: self-hosted
    needs: publish-test
    name: Update Container
    steps:
      - name: Update container in via watchtower
        run: |
          curl -H "Authorization: Bearer tokentokentokenlikeme" 192.168.1.100:8080/v1/update