name: Test and Build Docker Image and Push to Docker Hub under testing tag
run-name: ${{ github.actor }} is  ${{ github.event_name }} on ${{ github.repository }}
on: 
  push:
    branches:
      - 'main'
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

  test:
    runs-on: self-hosted
    steps:
      - run: docker build -t dematicscrewfixtrenthamdashboard_testing -f Dockerfile.testing . --progress=plain --no-cache
      - run: docker run dematicscrewfixtrenthamdashboard_testing
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          RUNNER_TOOL_CACHE: /toolcache
  build:
    runs-on: self-hosted
    needs: test
    steps:
      - run: docker build -t dematicscrewfixtrenthamdashboard .
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          RUNNER_TOOL_CACHE: /toolcache

  publish-test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push to Docker Hub
        run: |
          docker tag dematicscrewfixtrenthamdashboard:latest jwlyons/dematicscrewfixtrenthamdashboard:main
          docker push jwlyons/dematicscrewfixtrenthamdashboard:main
