name: Build and Test- Main Branch

on:
  push:
    branches:
      - main

jobs:
  Build_Test_and_Run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3

      - name: Build Test Image
        run: docker build -t dematicscrewfixtrenthamdashboard:testing -f Dockerfile.testing . --progress=plain --no-cache

      - name: Run Tests
        run: docker run --rm dematicscrewfixtrenthamdashboard:testing npm run test

  Build_Image:
    runs-on: self-hosted
    needs: Build_Test_and_Run

    steps:
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: dematicscrewfixtrenthamdashboard
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t dematicscrewfixtrenthamdashboard:latest -f Dockerfile . --progress=plain --no-cache

      - name: Push Image
        run: |
          docker tag dematicscrewfixtrenthamdashboard:latest jwlyons/dematicscrewfixtrenthamdashboard:latest
          docker push jwlyons/dematicscrewfixtrenthamdashboard:latest
          docker tag dematicscrewfixtrenthamdashboard:latest jwlyons/dematicscrewfixtrenthamdashboard:${{ steps.metadata.outputs.version }}
          docker push jwlyons/dematicscrewfixtrenthamdashboard:${{ steps.metadata.outputs.version }}

      - name: Remove Docker Images
        run: |
          docker rmi dematicscrewfixtrenthamdashboard:latest
          docker rmi jwlyons/dematicscrewfixtrenthamdashboard:latest
          docker rmi jwlyons/dematicscrewfixtrenthamdashboard:${{ steps.metadata.outputs.version }}
