name: Build and Test

on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v3

    - name: Build Test Image
      run: docker build -t dematicscrewfixtrenthamdashboard:testing -f Dockerfile . --progress=plain --no-cache

    - name: Run Tests
      run: docker run --rm dematicscrewfixtrenthamdashboard:testing npm run test

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: dematicscrewfixtrenthamdashboard
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Image 
      run : |
        docker build -t dematicscrewfixtrenthamdashboard:testing -f Dockerfile . --progress=plain --no-cache

    - name: Push Image
      run: |
        docker tag dematicscrewfixtrenthamdashboard:testing dematicscrewfixtrenthamdashboard:latest
        docker tag dematicscrewfixtrenthamdashboard:testing dematicscrewfixtrenthamdashboard:${{ steps.metadata.outputs.version }}
        docker push dematicscrewfixtrenthamdashboard:latest
        docker push dematicscrewfixtrenthamdashboard:${{ steps.metadata.outputs.version }}

      
