name: "coverage"
on:
  pull_request_target:
    branches:
      - master
      - main
      - testing
jobs:
  coverage:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - uses: ArtiomTr/jest-coverage-report-action@v2
